-- MySQL Script generated by MySQL Workbench
-- Sat Mar 14 14:16:51 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Person` (
  `Person_ID` INT NOT NULL,
  `First_Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Phone` INT NULL,
  `Password_Hash` VARCHAR(255) NULL,
  `Account_Status` ENUM('ACTIVE', 'SUSPENDED', 'DEACTIVATED', 'BANNED') NOT NULL,
  `Created_At` DATETIME NULL,
  PRIMARY KEY (`Person_ID`)
) ENGINE = InnoDB;

CREATE UNIQUE INDEX `Email_UNIQUE` ON `Person` (`Email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Customer` (
  `Person_ID` INT NOT NULL,
  `Default_Address_ID` INT NULL,
  `Loyalty_Points` INT NULL,
  `Preferred_Payment_Method` VARCHAR(45) NULL,
  PRIMARY KEY (`Person_ID`),
  CONSTRAINT `fk_Customer_Person`
    FOREIGN KEY (`Person_ID`)
    REFERENCES `Person` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Merchant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Merchant` (
  `Person_ID` INT NOT NULL,
  `Business_Name` VARCHAR(45) NULL,
  `Business_Type` VARCHAR(45) NULL,
  `Tax_ID` VARCHAR(45) NULL,
  `Approval_Status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED') NOT NULL,
  PRIMARY KEY (`Person_ID`),
  CONSTRAINT `fk_Merchant_Person1`
    FOREIGN KEY (`Person_ID`)
    REFERENCES `Person` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Driver` (
  `Person_ID` INT NOT NULL,
  `License_Number` VARCHAR(45) NULL,
  `Vehicle_Type` VARCHAR(45) NULL,
  `Background_Check_Status` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL,
  `Is_Online` TINYINT(1) NULL,
  `Rating_Avg` DECIMAL(3,2) NULL,
  PRIMARY KEY (`Person_ID`),
  CONSTRAINT `fk_Driver_Person1`
    FOREIGN KEY (`Person_ID`)
    REFERENCES `Person` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Admin` (
  `Person_ID` INT NOT NULL,
  `Role_Type` VARCHAR(45) NULL,
  `Access_Level` VARCHAR(45) NULL,
  PRIMARY KEY (`Person_ID`),
  CONSTRAINT `fk_Admin_Person1`
    FOREIGN KEY (`Person_ID`)
    REFERENCES `Person` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant` (
  `Restaurant_ID` INT NOT NULL,
  `Merchant_Person_ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Phone` INT NULL,
  `Description` VARCHAR(45) NULL,
  `Logo_URL` VARCHAR(45) NULL,
  `Status` ENUM('ACTIVE', 'INACTIVE', 'TEMP_CLOSED', 'SUSPENDED') NOT NULL,
  `Service_Radius_KM` DECIMAL(8,2) NULL,
  PRIMARY KEY (`Restaurant_ID`),
  CONSTRAINT `fk_Restaurant_Merchant1`
    FOREIGN KEY (`Merchant_Person_ID`)
    REFERENCES `Merchant` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Restaurant_Merchant1_idx` ON `Restaurant` (`Merchant_Person_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Opening_Hour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Opening_Hour` (
  `Opening_Hour_ID` INT NOT NULL AUTO_INCREMENT,
  `Restaurant_ID` INT NOT NULL,
  `Day_Of_Week` ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday') NOT NULL,
  `Open_Time` TIME NOT NULL,
  `Close_Time` TIME NOT NULL,
  PRIMARY KEY (`Opening_Hour_ID`),
  UNIQUE INDEX `uq_restaurant_day` (`Restaurant_ID` ASC, `Day_Of_Week` ASC) VISIBLE,
  CONSTRAINT `fk_Opening_Hour_Restaurant1`
    FOREIGN KEY (`Restaurant_ID`)
    REFERENCES `Restaurant` (`Restaurant_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Opening_Hour_Restaurant1_idx` ON `Opening_Hour` (`Restaurant_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Menu` (
  `Menu_ID` INT NOT NULL,
  `Restaurant_ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Is_Active` TINYINT(1) NULL,
  PRIMARY KEY (`Menu_ID`),
  CONSTRAINT `fk_Menu_Restaurant1`
    FOREIGN KEY (`Restaurant_ID`)
    REFERENCES `Restaurant` (`Restaurant_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Menu_Restaurant1_idx` ON `Menu` (`Restaurant_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Category` (
  `Category_ID` INT NOT NULL,
  `Menu_ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Sort_Order` INT NULL,
  PRIMARY KEY (`Category_ID`),
  CONSTRAINT `fk_Category_Menu1`
    FOREIGN KEY (`Menu_ID`)
    REFERENCES `Menu` (`Menu_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Category_Menu1_idx` ON `Category` (`Menu_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Item` (
  `Item_ID` INT NOT NULL,
  `Restaurant_ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Base_Price` DECIMAL(10,2) NULL,
  `Is_Available` TINYINT(1) NULL,
  `Image_URL` VARCHAR(45) NULL,
  PRIMARY KEY (`Item_ID`),
  CONSTRAINT `fk_Item_Restaurant1`
    FOREIGN KEY (`Restaurant_ID`)
    REFERENCES `Restaurant` (`Restaurant_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Item_Restaurant1_idx` ON `Item` (`Restaurant_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Category_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Category_Item` (
  `Item_ID` INT NOT NULL,
  `Category_ID` INT NOT NULL,
  PRIMARY KEY (`Item_ID`, `Category_ID`),
  CONSTRAINT `fk_Item_has_Category_Item1`
    FOREIGN KEY (`Item_ID`)
    REFERENCES `Item` (`Item_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_has_Category_Category1`
    FOREIGN KEY (`Category_ID`)
    REFERENCES `Category` (`Category_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Item_has_Category_Category1_idx` ON `Category_Item` (`Category_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Item_Option_Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Item_Option_Group` (
  `Group_ID` INT NOT NULL,
  `Item_ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Min_Select` INT NULL,
  `Max_Select` INT NULL,
  PRIMARY KEY (`Group_ID`),
  CONSTRAINT `fk_Item_Option_Group_Item1`
    FOREIGN KEY (`Item_ID`)
    REFERENCES `Item` (`Item_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Item_Option_Group_Item1_idx` ON `Item_Option_Group` (`Item_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Item_Option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Item_Option` (
  `Option_ID` INT NOT NULL,
  `Group_ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Price_Delta` DECIMAL(8,2) NULL,
  PRIMARY KEY (`Option_ID`),
  CONSTRAINT `fk_Item_Option_Item_Option_Group1`
    FOREIGN KEY (`Group_ID`)
    REFERENCES `Item_Option_Group` (`Group_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Item_Option_Item_Option_Group1_idx` ON `Item_Option` (`Group_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Address` (
  `Address_ID` INT NOT NULL,
  `Person_ID` INT NOT NULL,
  `Address_Type` ENUM('CUSTOMER', 'RESTAURANT') NULL,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `Zip` VARCHAR(45) NULL,
  `Lat` DECIMAL(9,6) NULL,
  `Lng` DECIMAL(9,6) NULL,
  `Instructions` VARCHAR(45) NULL,
  PRIMARY KEY (`Address_ID`),
  CONSTRAINT `fk_Address_Person1`
    FOREIGN KEY (`Person_ID`)
    REFERENCES `Person` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Address_Person1_idx` ON `Address` (`Person_ID` ASC) VISIBLE;

ALTER TABLE `Customer`
  ADD CONSTRAINT `fk_Customer_Default_Address1`
    FOREIGN KEY (`Default_Address_ID`)
    REFERENCES `Address` (`Address_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;


-- -----------------------------------------------------
-- Table `Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Order` (
  `Order_ID` INT NOT NULL,
  `Customer_Person_ID` INT NOT NULL,
  `Restaurant_ID` INT NOT NULL,
  `Delivery_Address_ID` INT NULL,
  `Order_Status` ENUM('PENDING', 'CONFIRMED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED') NOT NULL,
  `Subtotal` DECIMAL(10,2) NULL,
  `Tax` DECIMAL(10,2) NULL,
  `Delivery_Fee` DECIMAL(10,2) NULL,
  `Service_Fee` DECIMAL(10,2) NULL,
  `Tip` DECIMAL(10,2) NULL,
  `Total` DECIMAL(10,2) NULL,
  `Created_At` DATETIME NULL,
  PRIMARY KEY (`Order_ID`),
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_Person_ID`)
    REFERENCES `Customer` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Restaurant1`
    FOREIGN KEY (`Restaurant_ID`)
    REFERENCES `Restaurant` (`Restaurant_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Address1`
    FOREIGN KEY (`Delivery_Address_ID`)
    REFERENCES `Address` (`Address_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Order_Customer1_idx` ON `Order` (`Customer_Person_ID` ASC) VISIBLE;
CREATE INDEX `fk_Order_Restaurant1_idx` ON `Order` (`Restaurant_ID` ASC) VISIBLE;
CREATE INDEX `fk_Order_Address1_idx` ON `Order` (`Delivery_Address_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Order_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Order_Item` (
  `Order_Item_ID` INT NOT NULL,
  `Order_ID` INT NOT NULL,
  `Item_ID` INT NOT NULL,
  `Item_Name_Snapshot` VARCHAR(45) NULL,
  `Unit_Price` DECIMAL(10,2) NULL,
  `Quantity` INT NULL,
  `Notes` VARCHAR(45) NULL,
  PRIMARY KEY (`Order_Item_ID`),
  CONSTRAINT `fk_Order_Item_Order1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `Order` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Item_Item1`
    FOREIGN KEY (`Item_ID`)
    REFERENCES `Item` (`Item_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Order_Item_Order1_idx` ON `Order_Item` (`Order_ID` ASC) VISIBLE;
CREATE INDEX `fk_Order_Item_Item1_idx` ON `Order_Item` (`Item_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Order_Status_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Order_Status_History` (
  `History_ID` INT NOT NULL,
  `Order_ID` INT NOT NULL,
  `Status` ENUM('PLACED', 'CONFIRMED', 'PREPARING', 'READY_FOR_PICKUP', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'REFUNDED') NOT NULL,
  `Changed_At` DATETIME NULL,
  `Changed_By_Person_ID` INT NULL,
  PRIMARY KEY (`History_ID`),
  CONSTRAINT `fk_Order_Status_History_Order1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `Order` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Status_History_Person1`
    FOREIGN KEY (`Changed_By_Person_ID`)
    REFERENCES `Person` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Order_Status_History_Order1_idx` ON `Order_Status_History` (`Order_ID` ASC) VISIBLE;
CREATE INDEX `fk_Order_Status_History_Person1_idx` ON `Order_Status_History` (`Changed_By_Person_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Order_Item_Option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Order_Item_Option` (
  `ID` INT NOT NULL,
  `Order_Item_ID` INT NOT NULL,
  `Option_Name` VARCHAR(45) NULL,
  `Price_Delta` DECIMAL(10,2) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Order_Item_Option_Order_Item1`
    FOREIGN KEY (`Order_Item_ID`)
    REFERENCES `Order_Item` (`Order_Item_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Order_Item_Option_Order_Item1_idx` ON `Order_Item_Option` (`Order_Item_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Delivery` (
  `Delivery_ID` INT NOT NULL,
  `Order_ID` INT NOT NULL,
  `Driver_Person_ID` INT NOT NULL,
  `Status` ENUM('ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'FAILED', 'CANCELLED') NOT NULL,
  `Pickup_Time` DATETIME NULL,
  `Dropoff_Time` DATETIME NULL,
  `Distance_KM` DECIMAL(8,2) NULL,
  `Estimated_Duration` DECIMAL(8,2) NULL,
  PRIMARY KEY (`Delivery_ID`),
  CONSTRAINT `fk_Delivery_Order1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `Order` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Delivery_Driver1`
    FOREIGN KEY (`Driver_Person_ID`)
    REFERENCES `Driver` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Delivery_Order1_idx` ON `Delivery` (`Order_ID` ASC) VISIBLE;
CREATE INDEX `fk_Delivery_Driver1_idx` ON `Delivery` (`Driver_Person_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Driver_Location_Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Driver_Location_Log` (
  `Log_ID` INT NOT NULL,
  `Driver_Person_ID` INT NOT NULL,
  `Lat` DECIMAL(9,6) NULL,
  `Lng` DECIMAL(9,6) NULL,
  `Timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`Log_ID`),
  CONSTRAINT `fk_Driver_Location_Log_Driver1`
    FOREIGN KEY (`Driver_Person_ID`)
    REFERENCES `Driver` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Driver_Location_Log_Driver1_idx` ON `Driver_Location_Log` (`Driver_Person_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payment` (
  `Payment_ID` INT NOT NULL,
  `Order_ID` INT NOT NULL,
  `Provider` VARCHAR(45) NULL,
  `Provider_Transaction_ID` VARCHAR(45) NULL,
  `Amount` DECIMAL(10,2) NULL,
  `Currency` VARCHAR(45) NULL,
  `Status` ENUM('PENDING', 'AUTHORIZED', 'PAID', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED') NOT NULL,
  `Paid_At` DATETIME NULL,
  PRIMARY KEY (`Payment_ID`),
  CONSTRAINT `fk_Payment_Order1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `Order` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Payment_Order1_idx` ON `Payment` (`Order_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Refund`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Refund` (
  `Refund_ID` INT NOT NULL,
  `Payment_ID` INT NOT NULL,
  `Amount` DECIMAL(10,2) NULL,
  `Reason` VARCHAR(45) NULL,
  `Status` ENUM('REQUESTED', 'APPROVED', 'REJECTED', 'PROCESSED') NOT NULL,
  `Processed_At` DATETIME NULL,
  PRIMARY KEY (`Refund_ID`),
  CONSTRAINT `fk_Refund_Payment1`
    FOREIGN KEY (`Payment_ID`)
    REFERENCES `Payment` (`Payment_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Refund_Payment1_idx` ON `Refund` (`Payment_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rating` (
  `Rating_ID` INT NOT NULL,
  `Order_ID` INT NOT NULL,
  `Customer_Person_ID` INT NOT NULL,
  `Comment` VARCHAR(45) NULL,
  `Created_At` DATETIME NULL,
  PRIMARY KEY (`Rating_ID`),
  CONSTRAINT `fk_Rating_Customer1`
    FOREIGN KEY (`Customer_Person_ID`)
    REFERENCES `Customer` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rating_Order1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `Order` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Rating_Customer1_idx` ON `Rating` (`Customer_Person_ID` ASC) VISIBLE;
CREATE INDEX `fk_Rating_Order1_idx` ON `Rating` (`Order_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Support_Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Support_Ticket` (
  `Ticket_ID` INT NOT NULL,
  `Admin_Person_ID` INT NOT NULL,
  `Customer_ID` INT NULL,
  `Issue_Type` VARCHAR(45) NULL,
  `Status` ENUM('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'WAITING_FOR_CUSTOMER', 'RESOLVED', 'CLOSED') NOT NULL,
  `Created_At` DATETIME NULL,
  `Resolved_At` DATETIME NULL,
  PRIMARY KEY (`Ticket_ID`),
  CONSTRAINT `fk_Support_Ticket_Admin1`
    FOREIGN KEY (`Admin_Person_ID`)
    REFERENCES `Admin` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Support_Ticket_Customer1`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `Customer` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Support_Ticket_Admin1_idx` ON `Support_Ticket` (`Admin_Person_ID` ASC) VISIBLE;
CREATE INDEX `fk_Support_Ticket_Customer1_idx` ON `Support_Ticket` (`Customer_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Restaurant_Rating_ID`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant_Rating_ID` (
  `Rating_ID` INT NOT NULL,
  `Restaurant_ID` INT NOT NULL,
  `Score` TINYINT NULL,
  `Order_ID` INT NULL,
  PRIMARY KEY (`Rating_ID`),
  CONSTRAINT `fk_Restaurant_Rating_Rating1`
    FOREIGN KEY (`Rating_ID`)
    REFERENCES `Rating` (`Rating_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Restaurant_Rating_ID_Restaurant1`
    FOREIGN KEY (`Restaurant_ID`)
    REFERENCES `Restaurant` (`Restaurant_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Restaurant_Rating_ID_Order1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `Order` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Restaurant_Rating_Rating1_idx` ON `Restaurant_Rating_ID` (`Rating_ID` ASC) VISIBLE;
CREATE INDEX `fk_Restaurant_Rating_ID_Restaurant1_idx` ON `Restaurant_Rating_ID` (`Restaurant_ID` ASC) VISIBLE;
CREATE UNIQUE INDEX `Restaurant_Rating_Order_ID_UNIQUE` ON `Restaurant_Rating_ID` (`Order_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Driver_Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Driver_Rating` (
  `Rating_ID` INT NOT NULL,
  `Driver_Person_ID` INT NOT NULL,
  `Score` TINYINT NULL,
  `Order_ID` INT NULL,
  PRIMARY KEY (`Rating_ID`),
  CONSTRAINT `fk_Driver_Rating_Rating1`
    FOREIGN KEY (`Rating_ID`)
    REFERENCES `Rating` (`Rating_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Driver_Rating_Driver1`
    FOREIGN KEY (`Driver_Person_ID`)
    REFERENCES `Driver` (`Person_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Driver_Rating_Order1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `Order` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

CREATE INDEX `fk_Driver_Rating_Rating1_idx` ON `Driver_Rating` (`Rating_ID` ASC) VISIBLE;
CREATE INDEX `fk_Driver_Rating_Driver1_idx` ON `Driver_Rating` (`Driver_Person_ID` ASC) VISIBLE;
CREATE UNIQUE INDEX `Driver_Rating_Order_ID_UNIQUE` ON `Driver_Rating` (`Order_ID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
